### ISSUE TITLE
 Prototipação da tela de oferta de vagas.

### ISSUE THREAD

**Issue by annnyc** [annnyc/GRepublica#1]
Protótipo da tela de visualização de vagas no sistema, essa será a visão do usuário locador quando ele estiver procurando por alguma vaga.

**Comment by rafinhadufluxo** [comment]
Neste contexto ele verá apenas isso aqui.
![Info-aberto- vaga](https://user-images.githubusercontent.com/31291765/105078467-702a9380-5a64-11eb-879d-29c331e7e8a9.jpg)


Mas podemos melhorar neste caso a questão de detalhes da vaga.
