### ISSUE TITLE
Casos de uso: Suporte.

### ISSUE THREAD

**Issue by annnyc** [annnyc/GRepublica#13]
Criar os casos de uso do suporte.

**Comment by rafinhadufluxo** [comment]
O que podemos criar para gestão de suporte, apenas terá algumas solicitações de melhoria para o sistema ou daria suporte a atendimento ao cliente?
 @annnyc @Diegobecker07

**Comment by annnyc** [comment]
Creio que as principais atividades de suporte seriam:
- Atendimento ao cliente;
- Esclarecimento de dúvidas;
- Acompanhar o primeiro acesso do cliente no sistema, se solicitado;
- Captura de possíveis melhorias para o sistema através de feedbacks do cliente durante algum atendimento;

**Comment by rafinhadufluxo** [comment]
Este é o diagrama do suporte como poderá gerenciar o sistema, e o seu atendimento ao cliente. Achei simples a maneira que ele irá atuar. Vocês tem mais ideias para colocar nessa parte @annnyc @Diegobecker07 

Aberta a ideias para melhorar esse diagrama.

![Diagrama Suporte](https://user-images.githubusercontent.com/31291765/96820475-0f9fa200-13f4-11eb-90ad-551daea0ac19.png)
