### ISSUE TITLE
Descrição da page About.

### ISSUE THREAD

**Issue by rafinhadufluxo** [annnyc/GRepublica#20]
Nesse tópico, podemos retratar a visão da empresa. Como seus valores e metas, demostrando sua importância e como ela é útil no dia à  dia.

- Texto.
- Imagem ( utilizar no pixabay).

**Comment by rafinhadufluxo** [comment]
@Diegobecker07

**Comment by rafinhadufluxo** [comment]
Esse e o texto de apresentação do Quem somos. 

"A G-Republic foi criada com o intuito de facilitar a busca de imoveis, oferecendo uma plataforma conﬁável e segura para busca de apartamentos e republicas estudantil. A ideia do negócio surgiu da insatisfação da procura de um lar adequado, não poder atender as necessidades, sem dizer da falta de tempo.

Em pouco tempo de fundação, a empresa já colhe os frutos e possui em suas mãos no mercado imobiliário, movimentando e gerindo transações, provendo um serviço que acolhe cada vez mais usuários. Sua meta é oportunizar o acesso à cultura, promovendo um espaço onde os usuários se sintam livres para buscar imóvel do sonho, sem se preocupar com burocracias."

**Comment by rafinhadufluxo** [comment]
O que acham desta tela gente?

Deixo com fundo transparente, porém que deveria ter mais coisa escrita no About/ Quem somos, necessito da ajuda de  @voces?
![image](https://user-images.githubusercontent.com/31291765/100397555-a75e6480-3020-11eb-81c6-170d01017dfc.png)

**Comment by mazarafa** [comment]
@annnyc

**Comment by rafinhadufluxo** [comment]
Pessoal @annnyc  @Diegobecker07 ?

Acho legal mudar para este visual aqui, pois, toda empresa tem uma breve historia, visão e seus valores.  
![image](https://user-images.githubusercontent.com/31291765/100526160-9d617080-319c-11eb-9eb9-45fae04abf82.png)


Se vocês puderem dar uma pesquisada a respeito vai ser show!
