### ISSUE TITLE
G-contas

### ISSUE THREAD

**Issue by annnyc** [annnyc/GRepublica#27]
- gerenciador de contas
   - aluguel
   - condomínio
   - energia.
   - e outros.

**Comment by rafinhadufluxo** [comment]
Podemos fazer algo parecido com isso, mas diferente?

![image](https://user-images.githubusercontent.com/31291765/99260636-0981c300-27f2-11eb-9e15-6a4bb7543e94.png)

**Comment by annnyc** [comment]
sim, precisamos criar as estórias baseadas nisso

**Comment by annnyc** [comment]
pode ser sim, só temos que quebrar essa tela em tarefas menores pra alocar na sprint

**Comment by annnyc** [comment]
e temos que criar o banco que vai alocar essas informaçoes todas
