### ISSUE TITLE
Assinatura do cliente.

### ISSUE THREAD

**Issue by annnyc** [annnyc/GRepublica#28]

**Comment by rafinhadufluxo** [comment]
Como não tem um protótipo que relata bem o que seria uma assinatura, poderia mostrar os benefícios de ser G-Republica Pro, caso o usuário deseje ser no momento. Caso ele não deseje, ficará assim.
 
![image](https://user-images.githubusercontent.com/31291765/99112121-9135ba80-25c3-11eb-83b2-ed88c8b3c6bd.png)
