### ISSUE TITLE
Cadastro de vagas

### ISSUE THREAD

**Issue by annnyc** [annnyc/GRepublica#38]
**_Como_** usuário 
**_preciso_** cadastrar as vagas que possuo
**_para_** oferece-las  a possíveis locadores

**Comment by mazarafa** [comment]
No caso seria um post contendo detalhes do apartamento e localização, correto? 

Foi implementado algo simples que talvez represente melhor na pratica, logo abaixo o prototipo da tela de feed para posts.

![image](https://user-images.githubusercontent.com/31291765/103186412-d32a6f80-4896-11eb-99c4-aa1e9f2a2d41.png)

**Comment by rafinhadufluxo** [comment]
Podemos ressaltar que tivemos uma grande evolução com a questão de postagem, mas está sendo complicado integrar os dados no banco de dados nessa tecnologia. Mas em questão de front end está evoluindo rapidamente o projeto como está nesse print de tela de produção, aqui.
![image](https://user-images.githubusercontent.com/31291765/104248867-b5393f00-5440-11eb-990b-8c48cd7362d2.png)
