### ISSUE TITLE
Prototipação da tela de perfil do usuário.

### ISSUE THREAD

**Issue by annnyc** [annnyc/GRepublica#4]
Após o cadastro no sistema ter sido concluído o usuário poderá acessar essa tela para visualizar dados como a sua foto de perfil, vagas que oferta, nome e  e-mail, será uma espécie de perfil.

**Comment by rafinhadufluxo** [comment]
essa parte de locatorio e locador, serão a mesma pessoa. Vamos usar um método que junta os dois, se for possível!

**Comment by annnyc** [comment]
eu vejo que as duas devem ser tratadas de maneira diferente porque no perfil do locatário devem ser exibidas as vagas que ele ofertou, no do locador isso não irá ocorrer

**Comment by rafinhadufluxo** [comment]
Exato, mas imagine o seguinte. Usamos o exemplo do linkedin, o usuário pode  adicionar ofertas de emprego no local que trabalho e até mesmo fazer post da vida profissional e méritos. Neste caso, é mais fácil mesclar o mesmo usuário. Os dois terão mesmo acesso livre para fazer qualquer tipo de postagem referente ou visualização.

**Comment by rafinhadufluxo** [comment]
Refazendo o perfil do usuário, aonde poderá editar o nome, e alguns dados pessoais.

obs:Novamente, estou mudando  o designer.

![image](https://user-images.githubusercontent.com/31291765/98553838-67ecf580-2276-11eb-9a32-6b25b4eb229c.png)
