### ISSUE TITLE
Adicionar contas no gerenciador

### ISSUE THREAD

**Issue by annnyc** [annnyc/GRepublica#42]
Como usuário
preciso adicionar as contas do meu imóvel
para  saber quanto será gasto

**Comment by rafinhadufluxo** [comment]
Neste caso a tela poderia ser assim, bem simples.
![image](https://user-images.githubusercontent.com/31291765/102653929-145baa80-4146-11eb-8e93-9b4144f427e5.png)

**Comment by rafinhadufluxo** [comment]
Foi feito um pull resquest agora pouco com essa tela,  tem algo faltando nesse requisito de G-contas para mostrar o que o usuário gasta e ainda suas contas quando tiver uma integração .

observação: Falta implementação do back-end do para alimentar o banco.

Aberta para novas ideias e sugestões.
