### ISSUE TITLE
Tela do gerenciador

### ISSUE THREAD

**Issue by annnyc** [annnyc/GRepublica#43]
Como usuário
preciso acessar o gerenciador
para administrar meu imóvel

- A tela de apresentação deve  conter:

 * A data do período que será avaliado;
*  Opções de acesso as subtelas de gerencia: G-contas, G-Relatórios

**Comment by rafinhadufluxo** [comment]
Desenvolvimento da tela de contas da G-contas está concluida com sucesso (Desculpe a demora na sprint). Podemos observar que o usuário poderá adicionar alguma conta opcional, chamei de item  ainda tem uma paste delicada que se o usuario tiver contas no nome dele, o nosso sistema ja faz a integração com os valores e gerando um valor total, mostrando para aonde foi gasto em si.

logo abaixo, em anexo o print da tela.
![image](https://user-images.githubusercontent.com/31291765/102652001-ce9de280-4143-11eb-87b8-e5ad3428f018.png)
