### ISSUE TITLE
Prototipação da tela de cadastro.

### ISSUE THREAD

**Issue by annnyc** [annnyc/GRepublica#5]
Tela de cadastro de perfil do usuário no sistema.

**Comment by rafinhadufluxo** [comment]
concluído com sucesso a tela funcional de registro/cadastro. Falta revisar, se está de acordo com os requisitos do projeto.

![image](https://user-images.githubusercontent.com/31291765/98545773-59014580-226c-11eb-805c-3d016b791b02.png)
