### ISSUE TITLE
Pesquisa de viabilidade de chat

### ISSUE THREAD

**Issue by annnyc** [annnyc/GRepublica#51]
Estudar a viabilidade de implementação de um chat no sistema.

**Comment by rafinhadufluxo** [comment]
Acho valido essa questão de um chat, pois imagine que ..

"Eu usuário, estou interessado em um imove/ republica e quero saber como é as condições do imóvel e a vulnerabilidade do local. Se tem restrições/ defeitos no mesmo caso tenha e ainda mais informações sobre o locador."

Pensei muito nessa linha de pensamento, até porque, estamos divulgando vagas e apartamentos. Entretanto, so fazem postagem e nem tem curtida ou comentário, apenas tem interesse de visualização. O chat é apenas para conversar sobre o imóvel e ainda, caso o locátorio queira passar o contato dele para usuário interessado, pois,  o locátorio pode ou não adicionar no post seu contato para mais informações. Tem esse problema que deveria ser debatido real .

**Comment by annnyc** [comment]
Podemos tornar obrigatório para o locatário que ele informe o contato dele e o máximo possível de informações, esse controle fazemos no banco. O chat funcionaria mais para tirar dúvidas ou negociar, porque nem tudo poderemos forçar que o locatário informe, pode ser que a pessoa interessada queira saber de algo muito específico (por exemplo, se tem caixa d'agua no imóvel) e não queira ir pessoalmente verificar, acho que o chat seria bom nesse sentido pois da mais segurança aos envolvidos.

**Comment by rafinhadufluxo** [comment]
Concordo plenamente contigo, podemos acrescentar essa funcionalidade do projeto para próxima sprint ou não. Entretanto foi descrito no documento do projeto pelo Christian esse requisito de chat. Mas para final de semestre, não será implementado, caso alguém queira implementar está  disponível.
