### ISSUE TITLE
Prototipação da tela de login.

### ISSUE THREAD

**Issue by annnyc** [annnyc/GRepublica#6]
Prototipação da tela de login no sistema.

**Comment by rafinhadufluxo** [comment]
Com fim da prototipação feita anteriormente. Resolvi mudar algumas funcionalidades visual do website. Deixando o mesmo mais inspirador, de acordo com esse print logo abaixo. Contendo labels de login e senha para o usuário acessar no sistema.

![image](https://user-images.githubusercontent.com/31291765/98545257-9913f880-226b-11eb-847e-62867d913c77.png)
